CREATE TABLE IF NOT EXISTS `resume_address` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `resume_id` BIGINT UNSIGNED NULL,
  `address` VARCHAR(512) NOT NULL,
  `file_key` VARCHAR(256) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_user_resume_pdf` (`user_id`)
) ENGINE=InnoDB COMMENT='用户简历PDF地址表';
